#!/bin/sh

type="unknown"
verbose=no
stime=5

sleep=/bin/sleep
mpub=/usr/bin/mosquitto_pub

usage() {
    echo "Usage: ${0##*/} [-v] [-t type] [-s seconds] -- command [args...]" >&2
    exit 2
}

while getopts "vt:s:" options ; do
      case $options in
          v) verbose="yes"       ;;
          t) type="$OPTARG"       ;;
          s) stime="$OPTARG"      ;;
          *) usage                ;;
      esac
done
shift $((OPTIND-1))

# A command to supervise is mandatory
[ $# -ge 1 ] || usage

if [ "${verbose}" = "yes" ]; then
    set -x
fi

stop() {
    echo "Interruption requested!"
    exit 0
}

trap 'stop' INT TERM

notify() {
    [ -n "$MQTT_HOST" ] || return 0
    $mpub -h "${MQTT_HOST}"                                    \
          ${MQTT_PORT:+-p "${MQTT_PORT}"}                      \
          ${MQTT_USERNAME:+-u "${MQTT_USERNAME}"}              \
          ${MQTT_PASSWORD:+-P "${MQTT_PASSWORD}"}              \
          -t "${MQTT_TOPIC_PREFIX:-water-breaker}/error"      \
          -m "{ \"source\": \"$type\", \"type\": \"crash\", \"msg\": \"$1\" }"
}

while /bin/true ; do
    echo "Starting process"
    "$@"
    status=$?

    echo "Notifying of unexpected end (exit ${status})"
    notify "$type exited with status ${status}, restarting in ${stime}s."

    echo "Sleeping ${stime}s"
    $sleep "$stime"
done
