#!/bin/sh

# -- Config ------------------------------------------------------------

# That's bloody slow !!
#   -> you better hardcode the values
CONFIG_FILE=/root/moses/config.yaml
MQTT_HOST=`  yq -r '.[":mqtt"][":host"]'     "${CONFIG_FILE}"`
MQTT_PORT=`  yq -r '.[":mqtt"][":port"]'     "${CONFIG_FILE}"`
MQTT_USER=`  yq -r '.[":mqtt"][":username"]' "${CONFIG_FILE}"`
MQTT_PASSWD=`yq -r '.[":mqtt"][":password"]' "${CONFIG_FILE}"`

# yq emits "null" for missing keys; treat that as unset
for v in MQTT_PORT MQTT_USER MQTT_PASSWD ; do
    eval "[ \"\$$v\" = null ] && $v="
done

# ----------------------------------------------------------------------
# $NOTIFYTYPE / $UPSNAME / $HOSTNAME

# Path to commands
MOSQUITTO_PUB=/usr/bin/mosquitto_pub

# Notify
${MOSQUITTO_PUB}                                \
    -h "${MQTT_HOST}"                           \
    ${MQTT_PORT:+-p "${MQTT_PORT}"}             \
    ${MQTT_USER:+-u "${MQTT_USER}"}             \
    ${MQTT_PASSWD:+-P "${MQTT_PASSWD}"}         \
    -t "ups/${UPSNAME}/notify/${NOTIFYTYPE}"    \
    -m "$1"
